"use client";

import React, { useState } from "react";
import Button from "./ui/Button";
import Card from "./ui/Card";
import { api } from "@/lib/api";
import type { DemandLetter, RightsSummary, Checklist } from "@/lib/types";

/** The three types of legal actions CaseMate can generate from the user's profile context. */
type ActionType = "letter" | "rights" | "checklist";

/** Union type for all possible action generation results. */
type ActionResult = DemandLetter | RightsSummary | Checklist;

/**
 * Props for the ActionGenerator component.
 *
 * @property userId - The authenticated user's Supabase ID, used to fetch their
 *   profile context when generating actions
 */
interface ActionGeneratorProps {
  userId: string;
}

/**
 * Action generator toolbar for creating demand letters, rights summaries, and checklists.
 *
 * This is the demo-critical feature. It uses the user's legal profile and conversation
 * context to generate three types of actionable legal documents via the backend API:
 * - Demand letters with legal citations and pre-filled recipient details
 * - Rights summaries listing the user's specific entitlements under their state law
 * - Legal checklists with deadlines and concrete next steps
 *
 * Each generated result includes a copy-to-clipboard button and appropriate disclaimers.
 *
 * @param props - Component props
 * @param props.userId - The authenticated user's Supabase ID
 */
export default function ActionGenerator({ userId }: ActionGeneratorProps) {
  const [activeAction, setActiveAction] = useState<ActionType | null>(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<ActionResult | null>(null);
  const [resultType, setResultType] = useState<ActionType | null>(null);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  async function handleGenerate(action: ActionType) {
    setLoading(true);
    setActiveAction(action);
    setResult(null);
    setResultType(null);
    setError("");

    try {
      let data: ActionResult;
      switch (action) {
        case "letter":
          data = await api.generateLetter(userId);
          break;
        case "rights":
          data = await api.generateRights(userId);
          break;
        case "checklist":
          data = await api.generateChecklist(userId);
          break;
      }
      setResult(data);
      setResultType(action);
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "Failed to generate. Try again."
      );
    } finally {
      setLoading(false);
      setActiveAction(null);
    }
  }

  function getTextContent(): string {
    if (!result || !resultType) return "";
    switch (resultType) {
      case "letter":
        return (result as DemandLetter).letter_text;
      case "rights":
        return (result as RightsSummary).summary_text;
      case "checklist":
        return (result as Checklist).items.join("\n");
    }
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(getTextContent());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback: ignored
    }
  }

  function renderResult() {
    if (!result || !resultType) return null;

    switch (resultType) {
      case "letter": {
        const letter = result as DemandLetter;
        return (
          <Card>
            <Card.Header>
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-white">
                  Demand Letter
                </h3>
                <Button variant="ghost" size="sm" onClick={handleCopy}>
                  {copied ? "Copied!" : "Copy"}
                </Button>
              </div>
            </Card.Header>
            <Card.Body>
              <pre className="text-sm text-gray-200 whitespace-pre-wrap font-sans leading-relaxed">
                {letter.letter_text}
              </pre>
              {letter.legal_citations.length > 0 && (
                <div className="mt-4 pt-4 border-t border-white/[0.06]">
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
                    Legal Citations
                  </p>
                  <ul className="space-y-1">
                    {letter.legal_citations.map((cite: string, i: number) => (
                      <li key={i} className="citation">
                        {cite}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              <p className="trust-disclaimer">
                Generated by AI. Review with a licensed attorney before use.
              </p>
            </Card.Body>
          </Card>
        );
      }

      case "rights": {
        const rights = result as RightsSummary;
        return (
          <Card>
            <Card.Header>
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-white">
                  Rights Summary
                </h3>
                <Button variant="ghost" size="sm" onClick={handleCopy}>
                  {copied ? "Copied!" : "Copy"}
                </Button>
              </div>
            </Card.Header>
            <Card.Body>
              <p className="text-sm text-gray-200 leading-relaxed mb-4">
                {rights.summary_text}
              </p>
              {rights.key_rights.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
                    Key Rights
                  </p>
                  <ul className="space-y-1.5">
                    {rights.key_rights.map((right: string, i: number) => (
                      <li
                        key={i}
                        className="text-sm text-gray-300 flex gap-2"
                      >
                        <span className="text-green-400 shrink-0">&#10003;</span>
                        {right}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
              <p className="trust-disclaimer">
                Generated by AI. Review with a licensed attorney before use.
              </p>
            </Card.Body>
          </Card>
        );
      }

      case "checklist": {
        const checklist = result as Checklist;
        return (
          <Card>
            <Card.Header>
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-white">
                  Legal Checklist
                </h3>
                <Button variant="ghost" size="sm" onClick={handleCopy}>
                  {copied ? "Copied!" : "Copy"}
                </Button>
              </div>
            </Card.Header>
            <Card.Body>
              <ul className="space-y-2">
                {checklist.items.map((item: string, i: number) => (
                  <li key={i} className="flex items-start gap-3 text-sm">
                    <input
                      type="checkbox"
                      className="mt-0.5 rounded border-white/15 bg-white/[0.03] text-blue-500 focus:ring-blue-500/20 accent-blue-500"
                    />
                    <div>
                      <span className="text-gray-200">{item}</span>
                      {checklist.deadlines[i] && (
                        <span className="block text-xs text-red-400 mt-0.5">
                          Deadline: {checklist.deadlines[i]}
                        </span>
                      )}
                    </div>
                  </li>
                ))}
              </ul>
              <p className="trust-disclaimer">
                Generated by AI. Review with a licensed attorney before use.
              </p>
            </Card.Body>
          </Card>
        );
      }
    }
  }

  return (
    <div className="bg-white/[0.02] border-t border-white/10 px-6 py-3 shrink-0">
      {/* Action buttons */}
      <div className="flex items-center gap-2 mb-2">
        <span className="text-xs text-gray-500 mr-1">Actions:</span>
        <button
          onClick={() => handleGenerate("letter")}
          disabled={loading}
          className="px-3 py-1.5 text-sm font-medium text-gray-300 border border-white/10 rounded-lg hover:border-blue-500/30 hover:shadow-glow-sm transition-all disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading && activeAction === "letter" ? (
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 border border-gray-500 border-t-transparent rounded-full animate-spin" />
              Generating...
            </span>
          ) : (
            "Generate Letter"
          )}
        </button>
        <button
          onClick={() => handleGenerate("rights")}
          disabled={loading}
          className="px-3 py-1.5 text-sm font-medium text-gray-300 border border-white/10 rounded-lg hover:border-blue-500/30 hover:shadow-glow-sm transition-all disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading && activeAction === "rights" ? (
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 border border-gray-500 border-t-transparent rounded-full animate-spin" />
              Generating...
            </span>
          ) : (
            "Rights Summary"
          )}
        </button>
        <button
          onClick={() => handleGenerate("checklist")}
          disabled={loading}
          className="px-3 py-1.5 text-sm font-medium text-gray-300 border border-white/10 rounded-lg hover:border-blue-500/30 hover:shadow-glow-sm transition-all disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {loading && activeAction === "checklist" ? (
            <span className="flex items-center gap-1.5">
              <span className="w-3 h-3 border border-gray-500 border-t-transparent rounded-full animate-spin" />
              Generating...
            </span>
          ) : (
            "Checklist"
          )}
        </button>
      </div>

      {error && (
        <p className="text-xs text-red-400 bg-red-500/10 border border-red-500/20 rounded-lg p-2 mb-2">
          {error}
        </p>
      )}

      {result && <div className="max-h-64 overflow-y-auto">{renderResult()}</div>}
    </div>
  );
}
