"""PDF generation for legal documents and summaries.

Generates formatted PDF documents from demand letters, rights summaries,
checklists, and workflow outputs using fpdf2.
"""

from __future__ import annotations

from datetime import UTC, datetime

from fpdf import FPDF

from backend.utils.logger import get_logger

_logger = get_logger(__name__)

CASEMATE_DISCLAIMER: str = (
    "DISCLAIMER: This document was generated by CaseMate, an AI legal assistant. "
    "This is legal information, not legal advice. For advice specific to your "
    "situation, consult a licensed attorney in your state."
)


class CaseMatePDF(FPDF):
    """Branded PDF with CaseMate header and disclaimer footer."""

    def __init__(self, title: str = "", user_name: str = "") -> None:
        super().__init__()
        self._doc_title = title
        self._user_name = user_name
        self.set_auto_page_break(auto=True, margin=25)
        self.add_page()

    def header(self) -> None:
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(30, 64, 175)  # blue-700
        self.cell(0, 10, "CASEMATE - AI Legal Assistant", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 116, 139)  # gray-500
        now = datetime.now(UTC)
        self.cell(0, 5, f"Generated: {now.strftime('%B %d, %Y')}", new_x="LMARGIN", new_y="NEXT")
        if self._user_name:
            self.cell(0, 5, f"Prepared for: {self._user_name}", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(30, 64, 175)
        self.line(10, self.get_y() + 3, 200, self.get_y() + 3)
        self.ln(8)

    def footer(self) -> None:
        self.set_y(-22)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(148, 163, 184)
        self.multi_cell(0, 3, CASEMATE_DISCLAIMER)

    def add_title(self, title: str) -> None:
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(15, 23, 42)  # gray-900
        self.cell(0, 10, title.upper(), new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def add_body(self, text: str) -> None:
        self.set_font("Helvetica", "", 10)
        self.set_text_color(51, 65, 85)  # gray-700
        self.multi_cell(0, 5, text)
        self.ln(3)

    def add_section(self, heading: str, body: str) -> None:
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(30, 64, 175)
        self.cell(0, 8, heading.upper(), new_x="LMARGIN", new_y="NEXT")
        self.add_body(body)


def generate_text_document(
    title: str,
    content: str,
    user_name: str = "",
    sections: list[dict[str, str]] | None = None,
) -> bytes:
    """Generate a formatted PDF document.

    Args:
        title: Document title.
        content: Main document body text.
        user_name: Optional user name for personalization.
        sections: Optional additional sections with 'heading' and 'body' keys.

    Returns:
        PDF bytes.
    """
    pdf = CaseMatePDF(title=title, user_name=user_name)
    pdf.add_title(title)
    pdf.add_body(content)

    if sections:
        for section in sections:
            heading = section.get("heading", "")
            body = section.get("body", "")
            if heading or body:
                pdf.add_section(heading, body)

    doc_bytes = pdf.output()
    _logger.info("document_generated", title=title, length=len(doc_bytes))
    return bytes(doc_bytes)


def generate_demand_letter_document(
    letter_text: str,
    legal_citations: list[str],
    user_name: str = "",
) -> bytes:
    """Generate a formatted demand letter PDF.

    Args:
        letter_text: The demand letter body text.
        legal_citations: List of relevant legal citations.
        user_name: Optional user name.

    Returns:
        PDF bytes.
    """
    sections = []
    if legal_citations:
        sections.append(
            {
                "heading": "Legal Citations",
                "body": "\n".join(f"  - {cite}" for cite in legal_citations),
            }
        )

    return generate_text_document(
        title="Demand Letter",
        content=letter_text,
        user_name=user_name,
        sections=sections,
    )


def generate_rights_document(
    summary_text: str,
    key_rights: list[str],
    user_name: str = "",
) -> bytes:
    """Generate a formatted rights summary PDF.

    Args:
        summary_text: The rights summary text.
        key_rights: List of key rights.
        user_name: Optional user name.

    Returns:
        PDF bytes.
    """
    sections = []
    if key_rights:
        sections.append(
            {
                "heading": "Your Key Rights",
                "body": "\n".join(f"  {i}. {right}" for i, right in enumerate(key_rights, 1)),
            }
        )

    return generate_text_document(
        title="Rights Summary",
        content=summary_text,
        user_name=user_name,
        sections=sections,
    )


def generate_checklist_document(
    items: list[str],
    deadlines: list[str | None],
    user_name: str = "",
) -> bytes:
    """Generate a formatted checklist PDF.

    Args:
        items: List of checklist items.
        deadlines: List of deadline strings (parallel to items, None if no deadline).
        user_name: Optional user name.

    Returns:
        PDF bytes.
    """
    checklist_lines: list[str] = []
    for i, item in enumerate(items):
        deadline = deadlines[i] if i < len(deadlines) else None
        line = f"[ ] {item}"
        if deadline:
            line += f"\n      Deadline: {deadline}"
        checklist_lines.append(line)

    return generate_text_document(
        title="Legal Action Checklist",
        content="\n\n".join(checklist_lines),
        user_name=user_name,
    )
