"""PDF generation for legal documents and summaries.

Generates formatted PDF documents from demand letters, rights summaries,
checklists, and workflow outputs. Uses a simple HTML-to-text approach
for portability without heavy dependencies.
"""

from __future__ import annotations

from datetime import datetime

from backend.utils.logger import get_logger

_logger = get_logger(__name__)

LEX_DISCLAIMER: str = (
    "DISCLAIMER: This document was generated by Lex, an AI legal assistant. "
    "This is legal information, not legal advice. For advice specific to your "
    "situation, consult a licensed attorney in your state."
)


def generate_text_document(
    title: str,
    content: str,
    user_name: str = "",
    sections: list[dict[str, str]] | None = None,
) -> bytes:
    """Generate a formatted text document.

    Creates a professional text document with header, content sections,
    and disclaimer footer. Returns bytes suitable for download.

    Args:
        title: Document title.
        content: Main document body text.
        user_name: Optional user name for personalization.
        sections: Optional additional sections with 'heading' and 'body' keys.

    Returns:
        UTF-8 encoded bytes of the formatted document.
    """
    lines: list[str] = []

    # Header
    lines.append("=" * 70)
    lines.append("  LEX — AI Legal Assistant")
    lines.append(f"  Generated: {datetime.utcnow().strftime('%B %d, %Y')}")
    if user_name:
        lines.append(f"  Prepared for: {user_name}")
    lines.append("=" * 70)
    lines.append("")

    # Title
    lines.append(title.upper())
    lines.append("-" * len(title))
    lines.append("")

    # Main content
    lines.append(content)
    lines.append("")

    # Additional sections
    if sections:
        for section in sections:
            heading = section.get("heading", "")
            body = section.get("body", "")
            if heading:
                lines.append("")
                lines.append(heading.upper())
                lines.append("-" * len(heading))
            if body:
                lines.append(body)
            lines.append("")

    # Footer
    lines.append("")
    lines.append("-" * 70)
    lines.append("")
    lines.append(LEX_DISCLAIMER)
    lines.append("")
    lines.append(f"© {datetime.utcnow().year} Lex AI Legal Assistant")

    document_text = "\n".join(lines)
    _logger.info(
        "document_generated",
        title=title,
        length=len(document_text),
    )
    return document_text.encode("utf-8")


def generate_demand_letter_document(
    letter_text: str,
    legal_citations: list[str],
    user_name: str = "",
) -> bytes:
    """Generate a formatted demand letter document.

    Args:
        letter_text: The demand letter body text.
        legal_citations: List of relevant legal citations.
        user_name: Optional user name.

    Returns:
        UTF-8 encoded bytes of the formatted document.
    """
    sections = []
    if legal_citations:
        sections.append({
            "heading": "Legal Citations",
            "body": "\n".join(f"  • {cite}" for cite in legal_citations),
        })

    return generate_text_document(
        title="Demand Letter",
        content=letter_text,
        user_name=user_name,
        sections=sections,
    )


def generate_rights_document(
    summary_text: str,
    key_rights: list[str],
    user_name: str = "",
) -> bytes:
    """Generate a formatted rights summary document.

    Args:
        summary_text: The rights summary text.
        key_rights: List of key rights.
        user_name: Optional user name.

    Returns:
        UTF-8 encoded bytes of the formatted document.
    """
    sections = []
    if key_rights:
        sections.append({
            "heading": "Your Key Rights",
            "body": "\n".join(f"  {i}. {right}" for i, right in enumerate(key_rights, 1)),
        })

    return generate_text_document(
        title="Rights Summary",
        content=summary_text,
        user_name=user_name,
        sections=sections,
    )


def generate_checklist_document(
    items: list[str],
    deadlines: list[str | None],
    user_name: str = "",
) -> bytes:
    """Generate a formatted checklist document.

    Args:
        items: List of checklist items.
        deadlines: List of deadline strings (parallel to items, None if no deadline).
        user_name: Optional user name.

    Returns:
        UTF-8 encoded bytes of the formatted document.
    """
    checklist_lines: list[str] = []
    for i, item in enumerate(items):
        deadline = deadlines[i] if i < len(deadlines) else None
        line = f"  [ ] {item}"
        if deadline:
            line += f"\n      Deadline: {deadline}"
        checklist_lines.append(line)

    return generate_text_document(
        title="Legal Action Checklist",
        content="\n\n".join(checklist_lines),
        user_name=user_name,
    )
