/**
 * Translation dictionaries for CaseMate's English/Spanish UI.
 *
 * Every user-visible string in the app lives here. Components access
 * translations via the `useTranslation()` hook, which reads the current
 * language from LanguageContext.
 */

export type Locale = "en" | "es";

const translations = {
  // ──────────── Common / Shared ────────────
  loading: { en: "Loading...", es: "Cargando..." },
  loadingProfile: { en: "Loading your profile...", es: "Cargando tu perfil..." },
  retry: { en: "Retry", es: "Reintentar" },
  back: { en: "Back", es: "Atr\u00e1s" },
  next: { en: "Next", es: "Siguiente" },
  send: { en: "Send", es: "Enviar" },
  stop: { en: "Stop", es: "Detener" },
  cancel: { en: "Cancel", es: "Cancelar" },
  save: { en: "Save", es: "Guardar" },
  search: { en: "Search", es: "Buscar" },
  copy: { en: "Copy", es: "Copiar" },
  copied: { en: "Copied!", es: "\u00a1Copiado!" },
  close: { en: "Close", es: "Cerrar" },
  continue_: { en: "Continue", es: "Continuar" },

  // ──────────── Chat Interface ────────────
  chatGreeting: {
    en: (name: string, state: string) =>
      `Hi ${name}! I'm CaseMate, your AI legal assistant. I have your profile loaded for ${state}. How can I help you today?`,
    es: (name: string, state: string) =>
      `\u00a1Hola ${name}! Soy CaseMate, tu asistente legal de IA. Tengo tu perfil cargado para ${state}. \u00bfC\u00f3mo puedo ayudarte hoy?`,
  },
  chatPlaceholder: {
    en: "Describe your legal question...",
    es: "Describe tu pregunta legal...",
  },
  chatDisclaimer: {
    en: "AI assistant \u2014 not legal advice. Your data is encrypted and private.",
    es: "Asistente de IA \u2014 no es asesor\u00eda legal. Tus datos est\u00e1n cifrados y son privados.",
  },
  chatTitle: { en: "CaseMate", es: "CaseMate" },
  chatSubtitle: { en: "AI Legal Assistant", es: "Asistente Legal IA" },
  somethingWentWrong: {
    en: "Something went wrong. Please try again.",
    es: "Algo sali\u00f3 mal. Por favor, int\u00e9ntalo de nuevo.",
  },
  stopped: { en: "[Stopped]", es: "[Detenido]" },

  // ──────────── Navigation ────────────
  navRights: { en: "Rights", es: "Derechos" },
  navWorkflows: { en: "Workflows", es: "Procesos" },
  navDeadlines: { en: "Deadlines", es: "Plazos" },
  navAttorneys: { en: "Attorneys", es: "Abogados" },

  // ──────────── Conversation History ────────────
  newConversation: { en: "New conversation", es: "Nueva conversaci\u00f3n" },
  noPreviousConversations: {
    en: "No previous conversations",
    es: "No hay conversaciones previas",
  },

  // ──────────── Profile Sidebar ────────────
  memoryActive: { en: "Memory Active", es: "Memoria Activa" },
  memoryUpdated: { en: "Memory Updated", es: "Memoria Actualizada" },
  yourSituation: { en: "Your Situation", es: "Tu Situaci\u00f3n" },
  housing: { en: "Housing", es: "Vivienda" },
  employment: { en: "Employment", es: "Empleo" },
  family: { en: "Family", es: "Familia" },
  activeIssues: { en: "Active Issues", es: "Problemas Activos" },
  noActiveIssues: { en: "No active issues", es: "Sin problemas activos" },
  knownFacts: { en: "Known Facts", es: "Hechos Conocidos" },
  factsWillAppear: {
    en: "Facts will appear as you chat",
    es: "Los hechos aparecer\u00e1n mientras chateas",
  },
  documents: { en: "Documents", es: "Documentos" },
  noDocumentsUploaded: {
    en: "No documents uploaded",
    es: "No hay documentos subidos",
  },

  // ──────────── Action Generator ────────────
  actions: { en: "Actions:", es: "Acciones:" },
  generateLetter: { en: "Generate Letter", es: "Generar Carta" },
  rightsSummary: { en: "Rights Summary", es: "Resumen de Derechos" },
  checklist: { en: "Checklist", es: "Lista de Verificaci\u00f3n" },
  generating: { en: "Generating...", es: "Generando..." },
  failedToGenerate: {
    en: "Failed to generate. Try again.",
    es: "Error al generar. Int\u00e9ntalo de nuevo.",
  },
  demandLetter: { en: "Demand Letter", es: "Carta de Demanda" },
  legalCitations: { en: "Legal Citations", es: "Citas Legales" },
  keyRights: { en: "Key Rights", es: "Derechos Clave" },
  legalChecklist: { en: "Legal Checklist", es: "Lista Legal" },
  deadline: { en: "Deadline", es: "Plazo" },
  aiDisclaimer: {
    en: "Generated by AI. Review with a licensed attorney before use.",
    es: "Generado por IA. Rev\u00edsalo con un abogado licenciado antes de usar.",
  },

  // ──────────── Rights Library ────────────
  knowYourRights: { en: "Know Your Rights", es: "Conoce Tus Derechos" },
  browseByCategory: {
    en: "Browse legal rights guides by category",
    es: "Explora gu\u00edas de derechos legales por categor\u00eda",
  },
  selectGuidePrompt: {
    en: "Select a guide to learn about your rights",
    es: "Selecciona una gu\u00eda para conocer tus derechos",
  },
  allCategories: { en: "All categories", es: "Todas las categor\u00edas" },
  backToGuides: { en: "Back to guides", es: "Volver a las gu\u00edas" },
  guide: { en: "guide", es: "gu\u00eda" },
  guides: { en: "guides", es: "gu\u00edas" },
  whatYouNeedToKnow: {
    en: "What You Need to Know",
    es: "Lo Que Necesitas Saber",
  },
  yourRights: { en: "Your Rights", es: "Tus Derechos" },
  actionSteps: { en: "Action Steps", es: "Pasos a Seguir" },
  importantDeadlines: { en: "Important Deadlines", es: "Plazos Importantes" },
  commonMistakes: {
    en: "Common Mistakes to Avoid",
    es: "Errores Comunes a Evitar",
  },
  whenToGetLawyer: {
    en: "When to Get a Lawyer",
    es: "Cu\u00e1ndo Contratar un Abogado",
  },
  rightsDisclaimer: {
    en: "This is legal information, not legal advice. Consult a licensed attorney for your specific situation.",
    es: "Esto es informaci\u00f3n legal, no asesor\u00eda legal. Consulta a un abogado licenciado para tu situaci\u00f3n espec\u00edfica.",
  },

  // ──────────── Domain Labels ────────────
  domainLabels: {
    en: {
      landlord_tenant: "Housing & Tenant Rights",
      employment_rights: "Employment & Workplace",
      consumer_protection: "Consumer Protection",
      debt_collections: "Debt & Collections",
      traffic_violations: "Traffic & Driving",
      family_law: "Family Law",
      criminal_records: "Criminal Records",
      small_claims: "Small Claims Court",
      contract_disputes: "Contracts & Agreements",
      immigration: "Immigration",
    } as Record<string, string>,
    es: {
      landlord_tenant: "Vivienda y Derechos del Inquilino",
      employment_rights: "Empleo y Lugar de Trabajo",
      consumer_protection: "Protecci\u00f3n al Consumidor",
      debt_collections: "Deudas y Cobros",
      traffic_violations: "Tr\u00e1fico y Conducci\u00f3n",
      family_law: "Derecho Familiar",
      criminal_records: "Antecedentes Penales",
      small_claims: "Tribunal de Reclamos Menores",
      contract_disputes: "Contratos y Acuerdos",
      immigration: "Inmigraci\u00f3n",
    } as Record<string, string>,
  },

  // ──────────── Attorneys Page ────────────
  findAttorney: { en: "Find an Attorney", es: "Buscar un Abogado" },
  findAttorneyDescription: {
    en: "Find attorneys in your area who specialize in your legal issue",
    es: "Encuentra abogados en tu \u00e1rea que se especialicen en tu problema legal",
  },
  statePlaceholder: { en: "State (e.g., CA)", es: "Estado (ej. CA)" },
  zipPlaceholder: { en: "Zip code", es: "C\u00f3d. postal" },
  allAreas: { en: "All areas", es: "Todas las \u00e1reas" },
  noAttorneysFound: {
    en: "No attorneys found",
    es: "No se encontraron abogados",
  },
  tryBroadening: {
    en: "Try broadening your search criteria",
    es: "Intenta ampliar tus criterios de b\u00fasqueda",
  },
  enterStateToSearch: {
    en: "Enter a state to search for attorneys",
    es: "Ingresa un estado para buscar abogados",
  },
  freeConsult: { en: "Free consult", es: "Consulta gratis" },
  call: { en: "Call", es: "Llamar" },
  email: { en: "Email", es: "Correo" },
  website: { en: "Website", es: "Sitio web" },

  // Attorney legal area labels
  attorneyAreas: {
    en: {
      "": "All areas",
      landlord_tenant: "Housing & Tenant",
      employment_rights: "Employment",
      consumer_protection: "Consumer Protection",
      family_law: "Family Law",
      criminal_records: "Criminal Defense",
      immigration: "Immigration",
      debt_collections: "Debt & Collections",
      traffic_violations: "Traffic & DUI",
      small_claims: "Small Claims",
      contract_disputes: "Contracts",
    } as Record<string, string>,
    es: {
      "": "Todas las \u00e1reas",
      landlord_tenant: "Vivienda e Inquilinos",
      employment_rights: "Empleo",
      consumer_protection: "Protecci\u00f3n al Consumidor",
      family_law: "Derecho Familiar",
      criminal_records: "Defensa Penal",
      immigration: "Inmigraci\u00f3n",
      debt_collections: "Deudas y Cobros",
      traffic_violations: "Tr\u00e1fico y DUI",
      small_claims: "Reclamos Menores",
      contract_disputes: "Contratos",
    } as Record<string, string>,
  },

  // ──────────── Deadlines Page ────────────
  deadlinesTitle: { en: "Deadlines", es: "Plazos" },
  deadlinesDescription: {
    en: "Track your legal deadlines and statutes of limitations",
    es: "Sigue tus plazos legales y prescripciones",
  },
  addDeadline: { en: "+ Add Deadline", es: "+ Agregar Plazo" },
  deadlineTitlePlaceholder: {
    en: "Deadline title...",
    es: "T\u00edtulo del plazo...",
  },
  notesOptional: { en: "Notes (optional)...", es: "Notas (opcional)..." },
  saveDeadline: { en: "Save Deadline", es: "Guardar Plazo" },
  noActiveDeadlines: {
    en: "No active deadlines",
    es: "Sin plazos activos",
  },
  deadlinesAutoDetect: {
    en: "Deadlines will appear here as CaseMate detects them in your conversations",
    es: "Los plazos aparecer\u00e1n aqu\u00ed cuando CaseMate los detecte en tus conversaciones",
  },
  daysOverdue: {
    en: (n: number) => `${n} days overdue`,
    es: (n: number) => `${n} d\u00edas vencido`,
  },
  dueToday: { en: "Due today", es: "Vence hoy" },
  daysRemaining: {
    en: (n: number) => `${n} days remaining`,
    es: (n: number) => `${n} d\u00edas restantes`,
  },
  markComplete: { en: "Mark complete", es: "Marcar completado" },
  dismiss: { en: "Dismiss", es: "Descartar" },
  pastDeadlines: { en: "Past Deadlines", es: "Plazos Anteriores" },

  // ──────────── Workflows Page ────────────
  guidedWorkflows: { en: "Guided Workflows", es: "Procesos Guiados" },
  workflowsDescription: {
    en: "Step-by-step guides for common legal processes",
    es: "Gu\u00edas paso a paso para procesos legales comunes",
  },
  yourActiveWorkflows: {
    en: "Your Active Workflows",
    es: "Tus Procesos Activos",
  },
  availableWorkflows: {
    en: "Available Workflows",
    es: "Procesos Disponibles",
  },
  backToWorkflows: {
    en: "Back to workflows",
    es: "Volver a procesos",
  },
  startWorkflow: {
    en: "Start workflow \u2192",
    es: "Iniciar proceso \u2192",
  },
  steps: { en: "steps", es: "pasos" },
  step: { en: "Step", es: "Paso" },
  of: { en: "of", es: "de" },

  // ──────────── Workflow Wizard ────────────
  completed: { en: "Completed", es: "Completado" },
  requiredDocuments: {
    en: "Required Documents",
    es: "Documentos Requeridos",
  },
  tips: { en: "Tips", es: "Consejos" },
  deadlines: { en: "Deadlines", es: "Plazos" },
  previous: { en: "Previous", es: "Anterior" },
  markCompleteBtn: { en: "Mark Complete", es: "Marcar Completado" },
  saving: { en: "Saving...", es: "Guardando..." },

  // ──────────── Document Upload ────────────
  dragAndDrop: {
    en: "Drag and drop a document here, or",
    es: "Arrastra y suelta un documento aqu\u00ed, o",
  },
  browseFiles: { en: "Browse Files", es: "Buscar Archivos" },
  fileTypeHint: {
    en: "PDF, images, or text files up to 10MB",
    es: "PDF, im\u00e1genes o archivos de texto hasta 10MB",
  },
  uploading: { en: "Uploading...", es: "Subiendo..." },
  unsupportedFileType: {
    en: "Unsupported file type. Please upload PDF, images, or text files.",
    es: "Tipo de archivo no soportado. Sube PDF, im\u00e1genes o archivos de texto.",
  },
  fileTooLarge: {
    en: "File too large. Maximum size is 10MB.",
    es: "Archivo demasiado grande. El tama\u00f1o m\u00e1ximo es 10MB.",
  },
  uploadFailed: {
    en: "Upload failed. Please try again.",
    es: "Error al subir. Int\u00e9ntalo de nuevo.",
  },
  documentAnalysis: {
    en: "Document Analysis",
    es: "An\u00e1lisis de Documento",
  },
  summary: { en: "Summary", es: "Resumen" },
  keyFacts: { en: "Key Facts", es: "Hechos Clave" },
  redFlags: { en: "Red Flags", es: "Se\u00f1ales de Alerta" },
  docDisclaimer: {
    en: "Documents are analyzed locally and not shared with third parties.",
    es: "Los documentos se analizan localmente y no se comparten con terceros.",
  },

  // ──────────── Profile Page ────────────
  profile: { en: "Profile", es: "Perfil" },
  yourProfile: { en: "Your Profile", es: "Tu Perfil" },
  profileNotFound: { en: "Profile Not Found", es: "Perfil No Encontrado" },
  memberSince: { en: "Member since", es: "Miembro desde" },
  conversations: { en: "conversations", es: "conversaciones" },
  displayName: { en: "Display Name", es: "Nombre" },
  state: { en: "State", es: "Estado" },
  selectState: { en: "Select state", es: "Seleccionar estado" },
  housingSituation: { en: "Housing Situation", es: "Situaci\u00f3n de Vivienda" },
  employmentType: { en: "Employment Type", es: "Tipo de Empleo" },
  familyStatus: { en: "Family Status", es: "Estado Familiar" },
  saveChanges: { en: "Save Changes", es: "Guardar Cambios" },
  profileSaved: {
    en: "Profile saved successfully.",
    es: "Perfil guardado exitosamente.",
  },
  failedToSave: {
    en: "Failed to save profile.",
    es: "Error al guardar el perfil.",
  },
  failedToLoad: {
    en: "Failed to load profile.",
    es: "Error al cargar el perfil.",
  },
  knownLegalFacts: { en: "Known Legal Facts", es: "Hechos Legales Conocidos" },
  backToChat: { en: "Back to Chat", es: "Volver al Chat" },
  startOnboarding: { en: "Start Onboarding", es: "Iniciar Registro" },
  unableToLoadProfile: {
    en: "Unable to Load Profile",
    es: "No se Pudo Cargar el Perfil",
  },
  profileNotFoundOnboarding: {
    en: "Profile not found. Please complete onboarding first.",
    es: "Perfil no encontrado. Por favor, completa el registro primero.",
  },

  // ──────────── Onboarding ────────────
  stepOf: {
    en: (current: number, total: number) => `Step ${current} of ${total}`,
    es: (current: number, total: number) => `Paso ${current} de ${total}`,
  },
  onboardingSecureNotice: {
    en: "Your information is stored securely and used only to personalize your legal guidance.",
    es: "Tu informaci\u00f3n se almacena de forma segura y se usa solo para personalizar tu asesor\u00eda legal.",
  },
  letsGetToKnowYou: {
    en: "Let's get to know you",
    es: "Vamos a conocerte",
  },
  onboardingPersonalizeNote: {
    en: "CaseMate uses this information to give you personalized guidance.",
    es: "CaseMate usa esta informaci\u00f3n para darte orientaci\u00f3n personalizada.",
  },
  yourName: { en: "Your Name", es: "Tu Nombre" },
  namePlaceholder: { en: "e.g. Sarah Chen", es: "ej. Mar\u00eda Garc\u00eda" },
  selectYourState: { en: "Select your state", es: "Selecciona tu estado" },
  housingSituationTitle: { en: "Housing Situation", es: "Situaci\u00f3n de Vivienda" },
  housingNote: {
    en: "This helps CaseMate understand tenant/homeowner rights that apply to you.",
    es: "Esto ayuda a CaseMate a entender los derechos de inquilino/propietario que te aplican.",
  },
  renter: { en: "Renter", es: "Inquilino" },
  homeowner: { en: "Homeowner", es: "Propietario" },
  other: { en: "Other", es: "Otro" },
  detailsOptional: { en: "Details (optional)", es: "Detalles (opcional)" },
  housingDetailPlaceholder: {
    en: "e.g. apartment, month-to-month lease",
    es: "ej. apartamento, contrato mes a mes",
  },
  employmentTypeTitle: { en: "Employment Type", es: "Tipo de Empleo" },
  employmentNote: {
    en: "Employment status affects your rights in many legal areas.",
    es: "El estado de empleo afecta tus derechos en muchas \u00e1reas legales.",
  },
  employmentDetailPlaceholder: {
    en: "e.g. tech industry, part-time",
    es: "ej. industria tecnol\u00f3gica, medio tiempo",
  },
  familyStatusTitle: { en: "Family Status", es: "Estado Familiar" },
  familyNote: {
    en: "Family situation can affect custody, benefits, and housing rights.",
    es: "La situaci\u00f3n familiar puede afectar la custodia, beneficios y derechos de vivienda.",
  },
  single: { en: "Single", es: "Soltero/a" },
  married: { en: "Married", es: "Casado/a" },
  divorced: { en: "Divorced", es: "Divorciado/a" },
  widowed: { en: "Widowed", es: "Viudo/a" },
  domesticPartnership: { en: "Domestic Partnership", es: "Uni\u00f3n de Hecho" },
  numberOfDependents: {
    en: "Number of Dependents (optional)",
    es: "N\u00famero de Dependientes (opcional)",
  },
  currentLegalIssue: { en: "Current Legal Issue", es: "Problema Legal Actual" },
  legalIssueNote: {
    en: "Optionally describe a legal issue you're dealing with. You can always add this later.",
    es: "Opcionalmente describe un problema legal que est\u00e9s enfrentando. Siempre puedes agregarlo despu\u00e9s.",
  },
  legalIssuePlaceholder: {
    en: "e.g. My landlord hasn't returned my security deposit after 45 days...",
    es: "ej. Mi arrendador no ha devuelto mi dep\u00f3sito de seguridad despu\u00e9s de 45 d\u00edas...",
  },
  preferredLanguage: { en: "Preferred Language", es: "Idioma Preferido" },
  languageNote: {
    en: "Choose the language CaseMate will use when responding to you. You can change this anytime from your profile sidebar.",
    es: "Elige el idioma que CaseMate usar\u00e1 al responderte. Puedes cambiarlo en cualquier momento desde la barra lateral de tu perfil.",
  },
  english: { en: "English", es: "English" },
  spanish: { en: "Espa\u00f1ol", es: "Espa\u00f1ol" },
  settingUp: { en: "Setting up...", es: "Configurando..." },
  mustBeSignedIn: {
    en: "You must be signed in. Redirecting...",
    es: "Debes iniciar sesi\u00f3n. Redirigiendo...",
  },

  // ──────────── Audio Recorder ────────────
  voiceInput: { en: "Voice input", es: "Entrada de voz" },
  closeRecorder: { en: "Close recorder", es: "Cerrar grabadora" },

  // ──────────── Case History ────────────
  hideHistory: { en: "Hide history", es: "Ocultar historial" },
  showHistory: { en: "Show history", es: "Mostrar historial" },
} as const;

export type TranslationKey = keyof typeof translations;

export default translations;
